### ISSUE TITLE
Integrate localized sites 

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/search.quarkus.io#102]
The PR at https://github.com/quarkusio/quarkusio.github.io/pull/1825 integrates quarkus.io with search.quarkus.io, but currently we didn't do anything to have localized version of the website (e.g. ja.quarkus.io) use a different language in their calls to search.quarkus.io.

We should work on that.

**Comment by yrodiere** [comment]
Hey @ynojima , @rdnovell , in order to enable language-specific search on localized quarkus.io sites, I would need to override a piece of Jekyll config when those localized sites are built. Specifically, this piece: https://github.com/quarkusio/quarkusio.github.io/pull/1825/files#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R28-R30

I've looked around but didn't find any language-specific changes to config in [the build workflow](https://github.com/quarkusio/ja.quarkus.io/blob/main/.github/workflows/build.yml) or [quarkus-l10n-utils](https://github.com/doc-l10n-kit/quarkus-l10n-utils).

I suppose we could add a step to the workflow to to a simple `sed` on the `_config.yaml` file. Or we could enable translation for (specific parts of) `_config.yaml`, and translate `language: en` to `language: ja`.

Would you have a suggestion regarding the best approach here?

**Comment by ynojima** [comment]
I have prepared these changes to override jekyll language config:
https://github.com/quarkusio/ja.quarkus.io/pull/1101/files
https://github.com/doc-l10n-kit/quarkus-l10n-utils/pull/1/files

**Comment by yrodiere** [comment]
That's great, thank you! Can I assume other localized sites rely on the same scripts and will just need a PR similar to https://github.com/quarkusio/ja.quarkus.io/pull/1101/files ?

**Comment by yrodiere** [comment]
> That's great, thank you! Can I assume other localized sites rely on the same scripts and will just need a PR similar to https://github.com/quarkusio/ja.quarkus.io/pull/1101/files ?

Apparently I can:

![image](https://github.com/quarkusio/search.quarkus.io/assets/412878/ca863e43-941a-4b8e-9290-43951fa3aa9a)

Looks like we're good now, thanks!
