### ISSUE TITLE
Wait some time for the backend to be ready for indexing on startup

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/search.quarkus.io#144]
We just had an indexing failure in prod caused by the whole cluster being restarted:

> This is what happens when the app starts before the backend is ready.
> Maybe we should add some step to wait for the backend to be ready before attempting to index?

_Originally posted by @yrodiere in https://github.com/quarkusio/search.quarkus.io/issues/130#issuecomment-1893598706_

**Comment by yrodiere** [comment]
Important: I think we really only should wait for the indexing-on-start feature. It doesn't make sense to wait in the case of the periodic reindexing or when indexing is explicitly triggered through the management interface.

**Comment by yrodiere** [comment]
Hmm, actually we already do have such code:

https://github.com/quarkusio/search.quarkus.io/blob/6ae7d58a2f115ef8b3ae7bd09c931df9458fc60e/src/main/java/io/quarkus/search/app/indexing/IndexingService.java#L96-L117

But it doesn't work... I'll have a look

**Comment by yrodiere** [comment]
Ok, so, actually, what happens is that the first backend node is up, so the check passes, but other nodes are down, so the next request sent through the client will try to target other nodes (it's a round-robin of sorts) and fail. See https://github.com/quarkusio/search.quarkus.io/issues/131#issuecomment-1893594780

We'd need some sort of failover, and I though there was one... but apparently not :/

**Comment by marko-bekhta** [comment]
Maybe checking for cluster health would work?
https://opensearch.org/docs/2.11/api-reference/cluster-api/cluster-health/#example

**Comment by yrodiere** [comment]
Right, I'll try that.

Though if failover doesn't work, we have a bug: our tests expect it to work, see https://github.com/hibernate/hibernate-search/blob/94c571c53c35a92257bede06edfb7f4bc3dd50f3/integrationtest/backend/elasticsearch/src/test/java/org/hibernate/search/integrationtest/backend/elasticsearch/client/ElasticsearchClientFactoryImplIT.java#L599-L722

**Comment by yrodiere** [comment]
FWIW running this locally, with opensearch already running on port 9200, works as expected (i.e. there is failover):

```shell
quarkus dev -Dquarkus.devservices.enabled=false -Dquarkus.hibernate-search-orm.elasticsearch.hosts=localhost:9200,bar:9200,foobar:9200 -Dindexing.on-startup.when=always
```
