### ISSUE TITLE
Weird proposal from the browser in the search field

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#231]
I'm not sure where it comes from but I searched for Hibernate ORM once and then I had this weird popup suggesting `hibernate-orm`.

Not sure if it's a browser thing or something coming from the script but it's a bit annoying.
![Screenshot from 2024-04-12 18-06-20](https://github.com/quarkusio/search.quarkus.io/assets/1279749/89d31e0a-380c-4c6a-aa66-2e567e2750b9)

**Comment by marko-bekhta** [comment]
😔 I think it's from the browser on inputs .... if  `autocomplete="off"` attribute is added to that input the popup does not showup

**Comment by gsmet** [comment]
In that very case, I'm not sure it was very weird. (I was in the weird state I described in another issue and whatever I typed didn't get any search done).

I just tried again and I had:

![Screenshot from 2024-04-12 18-32-30](https://github.com/quarkusio/search.quarkus.io/assets/1279749/ed7dc700-1995-48a3-805b-323d86500876)

Which is less than ideal as it apparently reuses the searches from GitHub (this looks very very odd as I would expect this to be per website).

I'm not sure if we should disable autocomplete here (maybe?) but in any case we should probably not use `q` to avoid a conflict with GitHub `q`.

I'm not sure autocomplete has a lot of value in this case.

**Comment by yrodiere** [comment]
> Not sure if it's a browser thing or something coming from the script but it's a bit annoying.

Definitely a browser thing, I get this on plenty of websites.

> I'm not sure if we should disable autocomplete here (maybe?) but in any case we should probably not use q to avoid a conflict with GitHub q.

Agreed, let's rename `q` to something else, or let @ia3andy find the magic option to tell browsers "don't mix suggestions on this field with data from other websites" :)

**Comment by ia3andy** [comment]
If we rename it, this means we should also rename it on the search api.. unless we do some kind of magical mapping. I'll look if we can ignore those proposal some way.

**Comment by marko-bekhta** [comment]
> If we rename it, this means we should also rename it on the search api.. unless we do some kind of magical mapping. I'll look if we can ignore those proposal some way.

https://github.com/quarkusio/quarkusio.github.io/pull/1943 🙈
