### ISSUE TITLE
I searched once, cleared the field and didn't get to the home page with categories

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#232]
When clearing the search field, we should get to the default categorized UI and not all the guides sorted alphabetically.

![2024-04-12 18 10 46 quarkus io b7e5df4d5e59](https://github.com/quarkusio/search.quarkus.io/assets/1279749/a10e0a98-2e64-420b-86bb-a23dbc034798)

**Comment by yrodiere** [comment]
I reported that to @ia3andy when he sent his PR to quarkusio.github.io, but he had fixed it... I even saw it fixed myself. A regression perhaps?

**Comment by ia3andy** [comment]
Let's wait to see, I think it should be ok with the latest version

**Comment by yrodiere** [comment]
FWIW even trying right now, without the fix deployed, I can't reproduce your problem @gsmet :/

**Comment by ia3andy** [comment]
it should be fixed
