### ISSUE TITLE
After the first search, I can't get any search done

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#233]
I searched once and after that, whatever I typed, it doesn't do any search.

I see no error in the console, just the same results.

If I clear the search box entirely, I get all the results sorted alphabetically but if I type something else, it doesn't search either.

![2024-04-12 18 13 38 quarkus io a503feaaafd0](https://github.com/quarkusio/search.quarkus.io/assets/1279749/40ca0c3e-c946-4b21-ba30-d6083f01ce9d)

**Comment by gsmet** [comment]
Hmmm, this is weird. I tried it again and I can't reproduce it.

There's definitely something odd as I didn't do anything fancy the first time and it was in a very weird state.

**Comment by yrodiere** [comment]
@ia3andy This is probably something on the UI side.

**Comment by ia3andy** [comment]
I think we've found the issue with @marko-bekhta, he is working on a fix.

**Comment by yrodiere** [comment]
Fixed by #238
