### ISSUE TITLE
Do we need infinite loading?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#234]
@yrodiere I remember discussing that we should load all the results in one go given the number of results we have.

With his new version, I see some infinite loading, is it expected?

**Comment by yrodiere** [comment]
> @yrodiere I remember discussing that we should load all the results in one go given the number of results we have.

I remember saying that loading hundreds of results in one go didn't seem reasonable to me, and compromising by loading them 50 at a time.
