### ISSUE TITLE
When I don't have a local search service, I can't search for anything and the page just lists all the guides without the search at all

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#235]
We used to have a fallback and I think it's necessary for local development.

People need to be able to search for a guide even without a local search engine running or they won't be able to check their content, apart from knowing the URL or using the browser search which is less than ideal.

**Comment by yrodiere** [comment]
@ia3andy Seems the javascript search isn't working?

**Comment by ia3andy** [comment]
We discussed it with @gsmet I'll provide the fix, it's just a config issue
