### ISSUE TITLE
Add a param to configure icons color

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/search.quarkus.io#241]
Currently the icon colors is only defined in the web-comp, this needs to be a css param so we can change it to white from the parent.

![image](https://github.com/quarkusio/search.quarkus.io/assets/2223984/c17fe32e-5f9c-46a7-afde-e4976b328b9a)

**Comment by insectengine** [comment]
@ia3andy  - I've created dark versions of these graphics

**Comment by insectengine** [comment]
![docsicon-concepts-dark](https://github.com/quarkusio/search.quarkus.io/assets/928656/fbe9e67f-c485-47c1-99f3-b3f9a089b478)
![docsicon-guides-dark](https://github.com/quarkusio/search.quarkus.io/assets/928656/ca26e63f-778a-4de3-bf38-8eb426131483)
![docsicon-pdf-dark](https://github.com/quarkusio/search.quarkus.io/assets/928656/60562f9a-062c-4cc1-ad94-9ab6dc8a3cbc)
![docsicon-referencedocs-dark](https://github.com/quarkusio/search.quarkus.io/assets/928656/13501893-f142-45af-9378-d75f83134728)
![docsicon-tutorials-dark](https://github.com/quarkusio/search.quarkus.io/assets/928656/2632a88c-3f6a-4433-b32b-d4cf71d3e58f)

**Comment by insectengine** [comment]
They are light grey instead of white so they won't be as jarring for the user in dark mode (in a dark room).

**Comment by marko-bekhta** [comment]
Thanks! I think we can try using the same SVGs and CSS (either `fill` or maybe `invert`).
