### ISSUE TITLE
Clearing the serach input by clicking x does not keep the category filter

### ISSUE THREAD

**Issue by marko-bekhta** [quarkusio/search.quarkus.io#252]
1. Pick a category e.g. `Data`
2. Search for something, e.g. `orm`
3. Click `x` in the search input. 
  - text cleared
  - category filter stays unchanged
  - Search results resets to the initial page with group sections.

![Peek 2024-04-24 22-19](https://github.com/quarkusio/search.quarkus.io/assets/4004823/ff60fb41-a82d-4400-a329-779c89087b79)

We should either reset the category filter as well, or make sure that the guides are filtered by the category

**Comment by yrodiere** [comment]
If only there were entire JS frameworks designed to take care of that entire class of statefulness problem automatically... say vue.js... :]

**Comment by ia3andy** [comment]
> If only there were JS frameworks designed to take care of that entire class of statefulness problem automatically... say vue.js... :]

The logic with VueJS was pretty similar, no? I wonder what would take care of this kind of issue in VueJS

Also, obviously, you can't compare a full blown SPA framework with native browser features (web-components). Have a look at mvnpm.org, it all made with Lit web-components and the result is pretty nice.
