### ISSUE TITLE
Search sometimes fail or displays partial results

### ISSUE THREAD

**Issue by gsmet** [quarkusio/search.quarkus.io#320]
This happens quite often, generally when loading the search for the first time.

I had a bunch of errors like that in my log, not sure if they are related:

```
Uncaught (in promise) TypeError: URL constructor: /guides/spring-cloud-config-client is not a valid URL.
relativizeUrl https://quarkus.io/assets/javascript/search-wc.js:22
render https://quarkus.io/assets/javascript/search-wc.js:10
update https://quarkus.io/assets/javascript/search-wc.js:3
performUpdate https://quarkus.io/assets/javascript/search-wc.js:1
scheduleUpdate https://quarkus.io/assets/javascript/search-wc.js:1
_$ET https://quarkus.io/assets/javascript/search-wc.js:1
```

My understanding is that you cannot pass relative URLs to `new URL(...)`. Now why is the URL relative in some cases and not others, no idea. Maybe a timing issue?

**Comment by marko-bekhta** [comment]
We've tracked it down with Guillaume to be related to the local search. This patch https://github.com/quarkusio/search.quarkus.io/pull/321 will address the problem with the relative URL error in the console.

As to the initial slow response times and switching to the local search as a result, it may be related to https://github.com/quarkusio/search.quarkus.io/issues/49 

I'll merge the patch for the local search and deploy it, but maybe let's keep the issue open to see if we can figure out the slowness...

**Comment by yrodiere** [comment]
Can't the initial slow response simply come from OpenSearch doing some lazy initialization?

Anyway, I'd recommend closing this issue and opening another one, or reopening #49, because the current issue description has nothing to do with slowness.

**Comment by gsmet** [comment]
@yrodiere I agree about this particular issue being closed. Thanks @marko-bekhta .

As for the slowness, I don't think it's class loading as it's on quarkus.io and I don't suppose we spawn a new app for every request.

**Comment by yrodiere** [comment]
Okay, continuing the discussion on #49.

Indeed, thank you Marko, and thank you Guillaume for reporting.
