### ISSUE TITLE
Migrate from OpenSearch to Elasticsearch

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/search.quarkus.io#358]
When we first deployed search.quarkus.io, we ended up using OpenSearch instead of Elasticsearch in search.quarkus.io for license reasons. Recent performance problems are leading @marko-bekhta and me to reconsider.

## Problem

Running OpenSearch with a 1GB heap (e.g. for tests, or on staging) with aggressive indexing frequently trips the memory circuit breakers (protection against OOMError).

It's not a leak, rather GC not happening soon enough, because some time after tripping the circuit breaker, memory gets back to normal. Maybe the circuit breaker limit is _slightly_ below the point where the GC would kick in?

Anyway, I see several issues in the OpenSearch tracker about increased memory pressure, especially on OpenJDK 21+. So I suspect it's just a known issue. I don't particularly want to spend days debugging heap dumps, so left it at that.

## Solutions

Increasing memory available to OpenSearch is not really an option, as the cluster we deploy to is small, and experience has shown that it frequently can't find nodes to deploy our containers to when we ask for too much resources.

Marko tried to switch to Elasticsearch 8.15 (#357) and... The problem simply goes away:

* I get the problem most of the time when running tests with OpenSearch.
* I didn't get the problem at all in 5+ test runs with Elasticsearch -- same for Marko.

## Conclusion

Unless someone has valid objections, I think we'll just switch back to Elasticsearch. I personally don't see a problem with that:

* Starting with the next version (8.16), Elasticsearch is going to be licensed under AGPL, so the license is a not a problem anymore.
* We're not relying on any feature that is specific to OpenSearch, and are using Hibernate Search anyway, which abstracts away most of the  differences between Elasticsearch and OpenSearch.

So it seems to me that migrating will just be easier than debugging OpenSearch memory issues. The only pain point will be the OpenShift config -- but I'm hopeful there, as I had initially started deployment to OpenShift with Elasticsearch, and it had gone relatively smoothly.

**Comment by gsmet** [comment]
+1 from me.

**Comment by gsmet** [comment]
Just to clarify my +1, it wasn't added lightly.

The Elasticsearch client embedded in the application is ASL-licensed and the Elasticsearch server is only contacted through REST APIs and can be replaced by Opensearch so the AGPL propagation doesn't actually concern us from what I understood from AGPL.
