### ISSUE TITLE
Parse `_data/version/*/index/quarkus.yaml` instead of asciidoc files to retrieve guide metadata

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/search.quarkus.io#44]
These files are generated from asciidoc and known to match what quarkus.io will display.

Example: https://github.com/quarkusio/quarkusio.github.io/blob/develop/_data/versioned/latest/index/quarkus.yaml

In particular, guides that don't have a `:summary:` in the asciidoc still have a `summary` in those files... extracted from the preamble, maybe?

@gsmet This will require that we include additional metata (e.g. keywords/topics) in `_data/version/*/index/quarkus.yaml` files... I don't know if that's a problem?

**Comment by gsmet** [comment]
Topics and extensions are already there.

I can add the keywords.

**Comment by gsmet** [comment]
Oh, keywords are there too already.

Note that they might not be there for the old versions, unfortunately.

**Comment by gsmet** [comment]
Note that we could disable the search service for the old versions if it gets too tricky, I don't think this would hurt.

**Comment by yrodiere** [comment]
> Maybe I was unclear but my point is that we could get things to work for Quarkus 3.5+ and instead of fighting things for the old version, we could disable the search service for them. And at some point, all versions will use the search service.

As you wish, but since I already have the code to parse the asciidoc, I could just do that for older versions, and rely on quarkus.yaml for newer versions.

**Comment by yrodiere** [comment]
> Note that they might not be there for the old versions, unfortunately.

I just checked, and keywords are not in `quarkus.yaml` for versions before `main`, but then there's no `:keywords:` in the corresponding asciidocs, either.

So we can safely switch to `quarkus.yaml` for all versions, without losing any metadata.
