### ISSUE TITLE
Report and skip guides whose HTML content cannot be retrieved or is invalid

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/search.quarkus.io#64]
Currently indexing will fail in such case, BUT if indexing fails the previous version of indexes will still be available for search, so we'll just continue serving request with outdated data.

However:

> Now, if not having rendered guides is a problem, maybe it should be tested and a warning being logged?
> Because it would be a pity to break indexing because something like that is in the way.

_Originally posted by @gsmet in https://github.com/quarkusio/search.quarkus.io/pull/57#discussion_r1410643794_

I think we'll need to do better than warnings, though, because it's always the same with warnings: if you don't notice them, they're useless...

Maybe we should indeed be more forgiving during indexing and log a warning, BUT find some way to report the warnings... I think Openshift supports some kind of alerts?

**Comment by marko-bekhta** [comment]
> I think we'll need to do better than warnings, though, because it's always the same with warnings: if you don't notice them, they're useless...

What if we create a health check, add it to some custom group and use that in some monitoring tool that would notify us when that check is "down"?

**Comment by marko-bekhta** [comment]
I've used this kind of polling and also logs monitoring in the past so that's why I've thought about it, but yeah let's wait and see what's available 😃. For now, there were no unexpected guides in the latest quarkus.io 😃

**Comment by yrodiere** [comment]
We've discussed this with @gsmet and most convenient way to address this would probably to report indexing failures to a GitHub issue that would get watched by https://status.quarkus.io/.

We'd report a hard failure (exception during indexing, service most likely down) as well as soft failure (some data was missing, service still up but degraded).

This could be coupled to a health check as suggested by Marko, but we'd need that check to be ignored by Openshift (an indexing failure shouldn't lead to restarting the container).
